export const data = [
    {
      currency: "US Dollar",
      symbol: "USD",
      availableBalance: 0.0,
      totalBalance: 0.0,
      totalDeposit: 0.0,
      totalWithdrawal: 0.0,
      totalOrder: 0,
      status: "Active",
    },
    {
      currency: "Bitcoin",
      symbol: "BTC",
      availableBalance: 0.0,
      totalBalance: 0.0,
      totalDeposit: 0.0,
      totalWithdrawal: 0.0,
      totalOrder: 0,
      status: "Inactive",
    },
    {
      currency: "Ethereum",
      symbol: "ETH",
      availableBalance: 0.0,
      totalBalance: 0.0,
      totalDeposit: 0.0,
      totalWithdrawal: 0.0,
      totalOrder: 0,
      status: "Inactive",
    },
    {
      currency: "Litecoin",
      symbol: "LTC",
      availableBalance: 0.0,
      totalBalance: 0.0,
      totalDeposit: 0.0,
      totalWithdrawal: 0.0,
      totalOrder: 0,
      status: "Inactive",
    },
    {
      currency: "Solana",
      symbol: "SOL",
      availableBalance: 0.0,
      totalBalance: 0.0,
      totalDeposit: 0.0,
      totalWithdrawal: 0.0,
      totalOrder: 0,
      status: "Inactive",
    },
  ];